

CREATE TABLE PROJECT(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_NAME VARCHAR(100) NOTT NULL,
    CONTACT_NO_1 VARCHAR(15) NOT NULL,
    CONTACT_NO_2 VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    "ADDRESS" VARCHAR(300) NOT NULL,
    "STATE" VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    RECEIVED_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    "LOCATION" VARCHAR(100) NOT NULL,
    "STATUS" VARCHAR(1) NOT NULL,
    BUILDERS_NAME VARCHAR(100) NOT NULL,
    TYPES_OF_BUILDING VARCHAR(1) NOT NULL,
    PROJECT_BUILD_UP_AREA VARCHAR(100) NOT NULL,
    IS_SOIL_REPORT VARCHAR (1) NOT NULL,
    SBC VARCHAR(100) NOT NULL,
    TASK_LIST VARCHAR() NOT NULL,
    SOIL_REPORT_FILE  VARCHAR(255) NOT NULL,
    SOIL_REPORT_DESCRIPTON VARCHAR(500) NOT NULL,
    QUOTATION_AMOUNT DECIMAL NOT NULL,
    ADVANCE_AMOUNT DECIMAL NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL   
);

CREATE TABLE PROJECT_MANAGEMENT(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID BIGINT NOT NULL,
    TASK_ID BIGINT NOT NULL,
    ASSIGNEE_ID BIGINT NOT NULL,
    DUE_DATE DATE NOT NULL,
    STATUS_ID BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(500) NOT NULL,
    POINTS BIGINT NOTNULL,
    ACTUAL_COMPLETE_DATE DATE NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL 
);

CREATE TABLE PROJECT_MANAGEMENT_HISTORY(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_MANAGEMENT_ID BIGINT NOT NULL,
    "HISTORY" JSONB NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL 
);

CREATE TABLE PROJECT_MANAGEMENT_TASK_FILE(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_MANAGEMENT_ID BIGINT NOT NULL,
    FILE_NAME VARCHAR(100) NOT NULL,
    FILE_PATH VARCHAR(255) NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL 
);

CREATE TABLE ATTENDANCE_TRACKER(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID BIGINT NOT NULL,
    LOGIN_DATE_TIME TIMESTAMP NOT NULL,
    LOGOUT_DATE_TIME TIMESTAMP NOT NULL,
    "COMMENTS" VARCHAR(250) NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL 
);

CREATE TABLE TASK(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID BIGINT NOT NULL,
    TASK_ID BIGINT NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL 
);
INSERT INTO TASK (PROJECT_ID,TASK_ID,DELETED,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) 
VALUES(101,3001,'F','JHON',CURRENT_TIMESTAMP,'JHON',CURRENT_TIMESTAMP);

CREATE TABLE APP_USER(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "USER_NAME" VARCHAR(100) NOT NULL,
    "PASSWORD" VARCHAR(50) NOT NULL,
    MOBILE_NUMBER VARCHAR(15) NOT NULL,
    E_MAIL VARCHAR(255) NOT NULL,
    "ROLE" VARCHAR(1) NOT NULL,
    EXPIRY DATE NOT NULL,
    LAST_LOGIN DATE NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL 
);
INSERT INTO APP_USER ("USER_NAME","PASSWORD",MOBILE_NUMBER,E_MAIL,"ROLE",EXPIRY,
LAST_LOGIN,DELETED,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON)
VALUES('SIDD','DOGDOG7','7867772436','SIDD345@GMAIL.COM','A',CURRENT_DATE,CURRENT_DATE,
'F','DUO',CURRENT_TIMESTAMP,'F',CURRENT_TIMESTAMP);

CREATE TABLE EMPLOYEE(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(100) NOT NULL,
    MOBILE_NUMBER VARCHAR(15) NOT NULL,
    "POSITION" VARCHAR(1) NOT NULL,
    E_MAIL VARCHAR(255) NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL 
);


