USE EXPENSE_TRACKER;

CREATE TABLE `APP_USER` (
`ID` BIGINT AUTO_INCREMENT NOT NULL,
USERNAME VARCHAR(100) NOT NULL,
NAME VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
NAME VARCHAR(100) NOT NULL,
DELETED VARCHAR(1) NOT NULL,
CREATED_BY VARCHAR(50) NOT NULL,
CREATED_ON DATETIME NOT NULL,
UPDATED_BY VARCHAR(50),
UPDATED_ON DATETIME,
PRIMARY KEY (`ID`)
);

CREATE TABLE `EXPENSE` (
`ID` BIGINT AUTO_INCREMENT NOT NULL,
EXPENSE_NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(100) NOT NULL,
AMOUNT DECIMAL(10,2) NOT NULL,
DELETED VARCHAR(1) NOT NULL,
CREATED_BY VARCHAR(50) NOT NULL,
CREATED_ON DATETIME NOT NULL,
UPDATED_BY VARCHAR(50),
UPDATED_ON DATETIME,
PRIMARY KEY (`ID`)
);

CREATE TABLE `INCOME` (
`ID` BIGINT AUTO_INCREMENT NOT NULL,
INCOME_NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(100) NOT NULL,
AMOUNT DECIMAL(10,2) NOT NULL,
DELETED VARCHAR(1) NOT NULL,
CREATED_BY VARCHAR(50) NOT NULL,
CREATED_ON DATETIME NOT NULL,
UPDATED_BY VARCHAR(50),
UPDATED_ON DATETIME,
PRIMARY KEY (`ID`)
);
